[build]
  command = "yarn build"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[functions.imageOptimiser]
  included_files = ["node_modules/sharp/**/*"]
  timeout = 30